### ISSUE TITLE
stack.yaml build failure

### ISSUE THREAD

**Issue by codygman** [leksah/leksah#133]
```shell
cody@cody-G46VW:~/source/unsorted/leksah$ stack install
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      gtk3: needed (>=0.13.9 && <0.14 && >=0.13.9 && <0.14 && >=0.13.9 && <0.14), but 0.13.8 found
      hlint: needed (>=1.9.21 && <1.10), but 1.9.20 found
      leksah-server: needed (>=0.15.0.4 && <0.16), but 0.15.0.3 found
    needed for package: leksah-0.15.1.0
```

I deleted the stack.yaml, ran `stack init`, got no matches, ran `stack solver` and it selected the ghc-7.10 resolver and wrote the following stack.yaml:

```yaml

flags:
  text:
    integer-simple: false
  ghcjs-dom:
    ghcjs: false
  jsaddle:
    ghcjs: false
packages:
- '.'
- data/leksah-welcome/
extra-deps:
- HTTP-4000.2.20
- HUnit-1.2.5.2
- QuickCheck-2.8.1
- StateVar-1.1.0.0
- adjunctions-4.2.1
- aeson-0.9.0.1
- ansi-terminal-0.6.2.1
- attoparsec-0.13.0.1
- attoparsec-conduit-1.1.0
- base-orphans-0.4.0
- bifunctors-5
- binary-shared-0.8.3
- blaze-builder-0.4.0.1
- blaze-html-0.8.0.2
- blaze-markup-0.7.0.2
- cairo-0.13.1.0
- cmdargs-0.10.13
- comonad-4.2.6
- conduit-1.2.4.2
- conduit-extra-1.1.9
- contravariant-1.3.1.1
- cpphs-1.19
- distributive-0.4.4
- dlist-0.7.1.1
- exceptions-0.8.0.2
- executable-path-0.0.3
- extra-1.3
- free-4.12.1
- ghc-paths-0.1.0.9
- ghcjs-codemirror-0.0.0.1
- ghcjs-dom-0.1.1.3
- gio-0.13.1.0
- glib-0.13.1.1
- gtk3-0.13.9
- gtksourceview3-0.13.1.5
- haddock-api-2.16.0
- haddock-library-1.2.0
- hamlet-1.2.0
- hashable-1.2.3.3
- haskell-lexer-1.0
- haskell-src-exts-1.16.0.1
- hlint-1.9.21
- hscolour-1.23
- hslogger-1.2.9
- hxt-9.3.1.15
- hxt-charproperties-9.2.0.1
- hxt-regex-xmlschema-9.2.0.2
- hxt-unicode-9.0.2.4
- jsaddle-0.2.0.5
- kan-extensions-4.2.2
- leksah-server-0.15.0.4
- lens-4.11.1
- lifted-base-0.2.3.6
- ltk-0.15.0.1
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- nats-1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- pango-0.13.1.0
- parallel-3.2.0.6
- parsec-3.1.9
- polyparse-1.11
- prelude-extras-0.4
- pretty-show-1.6.8.2
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- reflection-1.5.2.1
- regex-base-0.93.2
- regex-tdfa-1.2.0
- regex-tdfa-text-1.0.0.2
- resourcet-1.1.5
- scientific-0.3.3.8
- semigroupoids-5.0.0.2
- semigroups-0.16.2.2
- shakespeare-2.0.5
- split-0.2.2
- stm-2.4.4
- streaming-commons-0.1.12.1
- strict-0.3.2
- syb-0.5.1
- tagged-0.8.1
- text-1.2.1.1
- tf-random-0.5
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- uniplate-1.6.12
- unordered-containers-0.2.5.1
- utf8-string-1
- vado-0.0.5
- vcsgui-0.1.2.0
- vcswrapper-0.1.2
- vector-0.10.12.3
- void-0.7
- webkitgtk3-0.13.1.3
- webkitgtk3-javascriptcore-0.13.0.4
- zlib-0.6.1.1
resolver: ghc-7.10
```
It now appears to be installing fine with that stack.yaml.

**Comment by codygman** [comment]
It required installing gtk2hs-buildtools first. I thought I could just add it to my stack.yaml, but ended up having to install it globally (it chose gtk2hs-buildtools-0.13.0.4 from lts-2.16). I'm now building leksah again after installing that and verifying gtk2hsC2hs is on my path.

**Comment by rkarp** [comment]
Generally it's better to use the `lts` resolvers. the `ghc` resolvers have almost no packages, which is why `stack solver` added so many extra-deps to your config. `lts-2.22` together with an updated MinGW install might work.
`lts-3.0` doesn't work due to #156 and [this](https://github.com/commercialhaskell/stack/issues/796).

**Comment by jtojnar** [comment]
```yaml
flags: {}
packages:
- '.'
- data/leksah-welcome/
extra-deps:
- binary-shared-0.8.3
- ghcjs-codemirror-0.0.0.1
- ghcjs-dom-0.2.1.0
- gtksourceview3-0.13.2.0
- jsaddle-0.2.1.0
- leksah-server-0.15.0.7
- ltk-0.15.0.3
- regex-tdfa-text-1.0.0.2
- vado-0.0.5
- vcsgui-0.1.3.0
- vcswrapper-0.1.2
- webkitgtk3-0.14.1.0
- webkitgtk3-javascriptcore-0.13.1.0
- attoparsec-conduit-1.1.0
resolver: lts-2.22
```
works for me.
