### ISSUE TITLE
stack build alex happy does clone...

### ISSUE THREAD

**Issue by andrewufrank** [leksah/leksah#432]
following the stack build advice in a fresh directory with a fresh clone.
when i do 
stack build alex happy i get an error. i include also the stack.yaml, which should probably include an extra-deps? 
same error occurs again for `stack install haskell-gi` and `stack install gtk2hs-buildtools
`.
later i get errors for vcs-wrapper.

````
Warning: The following modules should be added to exposed-modules or other-modules in /home/frank/Workspace8/leksah/vendor/haskellVCSWrapper/vcswrapper/vcswrapper.cabal:
    - In vcswrapper component:
        VCSWrapper.Mercurial
        VCSWrapper.Svn

Missing modules in the cabal file are likely to cause undefined reference errors from the linker, along with other problems.
````

````
stack install alex happy
Cloning into '/home/frank/Workspace8/leksah/.stack-work/downloaded/ZskrMsrTA76g'...
remote: Counting objects: 20209, done.
remote: Total 20209 (delta 0), reused 0 (delta 0), pack-reused 20209
Receiving objects: 100% (20209/20209), 12.23 MiB | 908.00 KiB/s, done.
Resolving deltas: 100% (14859/14859), done.
No extra-dep setting found for package at URL:

https://github.com/basvandijk/haddock.git

This is usually a mistake, external packages should typically
be treated as extra-deps to avoid spurious test case failures.
There were multiple candidates for the Cabal entry "Main.hs" (/home/frank/Workspace8/leksah/vendor/haskellVCSGUI/vcsgui/src/Main.hs), picking /home/frank/Workspace8/leksah/vendor/haskellVCSGUI/vcsgui/src/exe/askpass/Main.hs
Copying from /home/frank/.stack/snapshots/x86_64-linux-nopie/lts-8.0/8.0.2/bin/alex to /home/frank/.local/bin/alex
Copying from /home/frank/.stack/snapshots/x86_64-linux-nopie/lts-8.0/8.0.2/bin/happy to /home/frank/.local/bin/happy

Copied executables to /home/frank/.local/bin/:
- alex
- happy
frank@santafe:~/Workspace8/leksah$ cat stack.yaml
resolver: lts-8.0
packages:
- '.'
- 'vendor/leksah-server'
- 'vendor/ltk'
- 'vendor/haskellVCSGUI/vcsgui'
#- 'vendor/yi'
- 'vendor/haskellVCSWrapper/vcswrapper'
- location:
    git: https://github.com/basvandijk/haddock.git
    commit: f4c5e46ded05a4b8884f5ad6f3102f79ff3bb127
  subdirs:
  - haddock-api

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- binary-shared-0.8.3
- ghcjs-dom-0.7.0.4
- ghcjs-dom-jsaddle-0.7.0.3
- gi-gtk-hs-0.3.4.0
- gi-gtksource-3.0.12
- gi-javascriptcore-4.0.11
- gi-soup-2.4.11
- gi-webkit2-4.0.11
- ref-tf-0.4.0.1
- jsaddle-0.8.0.1
- jsaddle-dom-0.7.1.0
- gi-gdk-3.0.11
- gi-gdkpixbuf-2.0.11
- gi-glib-2.0.11
- gi-gobject-2.0.11
- gi-gtk-3.0.11
- gi-cairo-1.0.11
- gi-gio-2.0.11
- gi-pango-1.0.11
- gi-atk-2.0.11

# Override default flag values for local packages and extra-deps
flags:
  gi-atk:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-cairo:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-gdk:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-gdkpixbuf:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-gio:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-glib:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-gobject:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-gtk:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-gtk-hs:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-gtksource:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-javascriptcore:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-pango:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-soup:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false
  gi-webkit2:
    overloaded-methods: false
    overloaded-signals: false
    overloaded-properties: false

# Extra package databases containing global packages
extra-package-dbs: []

````
