### ISSUE TITLE
leksah 16.2.2 with stack and multiple packages

### ISSUE THREAD

**Issue by andrewufrank** [leksah/leksah#434]
after several attemps I have a found method to use leksah with stack and multiple projects .
1. build leksah with the instruction for stack build (attention: clone with --recursive!)
2. start leksah with stack exec leksah in the directory it was built (the code you work on can be in another dir).
3. organize your project with multiple subprojects by adding to each project a stack.yaml file along the following example: 

````
flags: {}
extra-package-dbs: []
packages:
- '.'
- ../rdfhextension
- location: /home/frank/Workspace8/repo8/rdf4store
  extra-dep: true
- location: /home/frank/Workspace8/repo8/uniform/uniform-strings
  extra-dep: true
- location: /home/frank/Workspace8/repo8/uniform/uniform-error
  extra-dep: true

extra-deps:
resolver: lts-8.2
````

4. run sack solver and then stack solver --update-config in each project to test the stack.yaml file; 
5. delete all .stack-work directories 
6. open leksah, create a workspace in the directory above your packages.
6. add the package with the main programs to leksah (add package .. select the cabal file).
8. build the project in leksah
if you have difficulties with error messages regarding exports/imports, you can check in a terminal in your "main" package. `stack build --ghc-options "-fPIC" `
(leksah produces build with this flag by default, if you use the same flag, duplication of compilation and building is avoided -- does perhaps not work?).
alternative: delete the .stack-working directory of the exporting package. it will be rebuild and export the correct interface.
9. run your main program not with  `stack exec <prog name>` but just `<prog name>`, because leksah stores the executable in `.local/bin` (make sure this is first on your path). if you run `stack build` in this directory, then you can execute what is prouced there with `stack exec` - which is likely not the same as what leksah produced.

if nothing helps to enforce the imports of new exports, add a sub-sub version number in the exporting package and in the importing `depends` in the `.cabal` file. (better just delete `.stack-working` in the exporting package). 

if you wish to work with another package in your project (i.e. another package which has a Main.hs) just selecting the package in workspace is not sufficient, but you can delete the previous main package. 

it is not yet perfect -some duplication of compile and build - but it seems to work.
